spring:
  application:
    name: accounts-transactions-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:novobanco_db}
    username: ${DB_USER:novobanco}
    password: ${DB_PASSWORD:novobanco_pass}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      pool-name: NovoBancoPool

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        default_schema: public
    show-sql: false

server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: never
    include-binding-errors: never

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha

logging:
  level:
    com.novobanco: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
